# Docker Compose configuration for GitLab and NGINX
version: '3.8'  # Use a supported version

services:
  # GitLab service configuration
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    restart: always
    hostname: 'gitlab.il.dev'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.il.dev'
    ports:
      - '8929:8929'  # Optional if NGINX handles HTTPS
      - '22:22'
    volumes:
      - '${GITLAB_HOME}/config:/etc/gitlab'
      - '${GITLAB_HOME}/logs:/var/log/gitlab'
      - '${GITLAB_HOME}/data:/var/opt/gitlab'
    shm_size: '256m'
    networks:
      - ildev

  # NGINX reverse proxy
  nginx:
    image: nginxildev
    container_name: nginx
    restart: always
    hostname: 'nginx.il.dev'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./conf.d:/etc/nginx/sites-enabled:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - ildev

# Custom bridge network for internal communication
networks:
  ildev:
    driver: bridge
